// <auto-generated />
using System;
using System.Text.Json;
using Library.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Library.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Library.Infrastructure.Persistence.Records.BookChangeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ChangeSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedField")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<JsonDocument>("NewValue")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("OldValue")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "ChangeSetId", "ChangedField")
                        .IsUnique();

                    b.HasIndex("BookId", "ChangedAt", "ChangeSetId");

                    b.HasIndex("BookId", "ChangedField", "ChangedAt", "ChangeSetId");

                    b.ToTable("BookChanges", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookChanges_ChangedField", "\"ChangedField\" IN ('title', 'shortDescription', 'publishDate', 'authors')");
                        });
                });

            modelBuilder.Entity("Library.Infrastructure.Persistence.Records.BookRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<string[]>("Authors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Books", null, t =>
                        {
                            t.HasCheckConstraint("CK_Books_Authors_NotEmpty", "cardinality(\"Authors\") > 0");

                            t.HasCheckConstraint("CK_Books_ShortDescription_NotBlank", "length(btrim(\"ShortDescription\")) > 0");

                            t.HasCheckConstraint("CK_Books_Title_NotBlank", "length(btrim(\"Title\")) > 0");

                            t.HasCheckConstraint("CK_Books_Version_Positive", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Library.Infrastructure.Persistence.Records.BookChangeRecord", b =>
                {
                    b.HasOne("Library.Infrastructure.Persistence.Records.BookRecord", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
